points:
  - id: 50
    x: -695.0
    y: 535.0

  - id: 51
    x: -545.0
    y: 535.0

  - id: 52
    x: -395.0
    y: 535.0

  - id: 53
    x: -245.0
    y: 535.0

  - id: 54
    x: 307.5
    y: 150.0

  - id: 55
    x: 387.5
    y: 150.0

  - id: 56
    x: -387.5
    y: 0.0

  - id: 57
    x: -307.5
    y: 0.0

  - id: 58
    x: 307.5
    y: 0.0

  - id: 59
    x: 387.5
    y: 0.0

  - id: 60
    x: -387.5
    y: -150.0

  - id: 61
    x: -307.5
    y: -150.0

  - id: 62
    x: 245.0
    y: -535.0

  - id: 63
    x: 395.0
    y: -535.0

  - id: 64
    x: 545.0
    y: -535.0

  - id: 65
    x: 695.0
    y: -535.0